namespace: "kpeacocke"
name: "draytek"
version: 0.1.0
readme: README.md
authors:
  - "kpeacocke"
description: "Ansible collection for automating DrayTek DrayOS network devices."
license:
  - GPL-3.0-or-later
tags:
  - infrastructure
  - tools
  - networking
  - network
dependencies:
  ansible.netcommon: ">=6.0.0"
repository: ""
issues: ""
